version: '3.8'                      
services:                           
  postgres_db:                      
    image: postgres:16           
    restart: always                 
    environment:                     
     - POSTGRES_USER=usr
     - POSTGRES_PASSWORD=pwd
     - POSTGRES_DB=demoDB
     - PGDATA=/var/lib/postgresql/data/pgdata
    ports:                          
      - '5435:5432'
    volumes:                        
      - db-vol:/var/lib/postgresql/data            
volumes:                           
  db-vol:   
